Tennis.NET.Web/ViewModels/PlayerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tennis.NET.Models;

namespace Tennis.NET.Web.ViewModels
{
    public class PlayerViewModel
    {
        public int PlayerId { get; set; }

        [Required]
        [Display(Name = "Spelersnummer")]
        public int PlayerNr { get; set; }

        [MaxLength(50)]
        [Display(Name = "Achternaam")]
        public String PlayerLastName { get; set; }

        [MaxLength(50)]
        [Display(Name = "Voornaam")]
        public String PlayerFirstName { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Geboortedatum")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime? PlayerBirthDay { get; set; }

        [Display(Name = "Geslacht")]
        public Gender? PlayerGender { get; set; }

        [Display(Name = "Jaar van toetreding")]
        public int? PlayerYearOfJoin { get; set; }

        [Display(Name = "Straatnaam")]
        [MaxLength(50)]
        public String PlayerStreet { get; set; }

        [Display(Name = "Huisnr")]
        [Range(1, int.MaxValue)]
        public int? PlayerHouseNr { get; set; }

        [Display(Name = "Bus")]
        public String PlayerMailBox { get; set; }

        [Display(Name = "Postcode")]
        public String PlayerZipcode { get; set; }

        [Display(Name = "Gemeente")]
        public String PlayerCity { get; set; }

        [Display(Name = "Telefoonnr")]
        public String PlayerPhoneNr { get; set; }

        [Display(Name = "Federatienr")]
        public int? PlayerFederationNr { get; set; }

        [Display(Name = "Naam")]
        public String FullName
        {
            get
            {
                return PlayerLastName + " " + PlayerFirstName;
            }
        }

        public IEnumerable<SelectListItem> AllRoles { get; set; }

        public List<int> SelectedRoles { get; set; }
    }
}

Tennis.NET.Web/Controllers/FineController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tennis.NET.Models;
using Tennis.NET.DataModel;
using Tennis.NET.Repositories;

namespace Tennis.NET.Web.Controllers
{
    public class FineController : Controller
    {
        private FineRepository repo = new FineRepository();
        private PlayerRepository playerRepo = new PlayerRepository();

        // GET: /Fine/
        public ActionResult Index(int? playerId)
        {
            List<Fine> fines = repo.getFines();
            ViewBag.filter = false;
            if (playerId != null)
            {
                ViewBag.filter = true;
                List<Fine> filteredList = new List<Fine>();
                foreach(Fine f in fines)
                {
                    if (f.PlayerId == playerId)
                    {
                        filteredList.Add(f);
                    }
                }
                fines = filteredList;
            }
            return View(fines);
        }

        // GET: /Fine/Create
        public ActionResult Create()
        {
            ViewBag.PlId = new SelectList(playerRepo.getPlayers(), "Id", "FullName");
            return View();
        }

        // POST: /Fine/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,PlayerId,FineDate,Amount")] Fine fine)
        {
            if (ModelState.IsValid)
            {
                repo.createFine(fine);
                return RedirectToAction("Index");
            }

            ViewBag.PlId = new SelectList(playerRepo.getPlayers(), "Id", "FullName", fine.PlayerId);
            return View(fine);
        }

        // GET: /Fine/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fine fine = repo.getFineById(id);
            if (fine == null)
            {
                return HttpNotFound();
            }
            ViewBag.PlId = new SelectList(playerRepo.getPlayers(), "Id", "FullName", fine.PlayerId);
            return View(fine);
        }

        // POST: /Fine/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,PlayerId,FineDate,Amount")] Fine fine)
        {
            if (ModelState.IsValid)
            {
                repo.modifyFine(fine);
                return RedirectToAction("Index");
            }
            ViewBag.PlId = new SelectList(playerRepo.getPlayers(), "Id", "FullName", fine.PlayerId);
            return View(fine);
        }

        // GET: /Fine/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fine fine = repo.getFineById(id);
            if (fine == null)
            {
                return HttpNotFound();
            }
            return View(fine);
        }

        // POST: /Fine/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            repo.deleteFine(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tennis.NET.Web/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tennis.NET.Models;
using Tennis.NET.DataModel;
using Tennis.NET.Repositories;
using Tennis.NET.Web.ViewModels;

namespace Tennis.NET.Web.Controllers
{
    public class PlayerController : Controller
    {
        private PlayerRepository repo = new PlayerRepository();
        private RoleRepository roleRepo = new RoleRepository();

        // GET: /Player/
        public ActionResult Index()
        {
            return View(repo.getPlayers());
        }

        // GET: /Player/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = repo.getPlayerById(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }

        // GET: /Player/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Player/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,PlayerNr,LastName,FirstName,BirthDay,Gender,YearOfJoin,Street,HouseNr,MailBox,Zipcode,City,PhoneNr,FederationNr")] Player player)
        {
            if (ModelState.IsValid)
            {
                repo.createPlayer(player);
                return RedirectToAction("Index");
            }

            return View(player);
        }

        // GET: /Player/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = repo.getPlayerById(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            var allRolesList = roleRepo.getRoles();
            var allRolesSelect = allRolesList.Select(o => new SelectListItem
            {
                Text = o.Name,
                Value = o.Id.ToString()
            });
            var selectedRoles = player.Roles.Select(p => p.Id).ToList();
            PlayerViewModel pvm = new PlayerViewModel { PlayerId = player.Id, PlayerBirthDay = player.BirthDay, PlayerCity = player.City,
                PlayerFederationNr = player.FederationNr, PlayerFirstName = player.FirstName, PlayerGender = player.Gender, 
                PlayerHouseNr = player.HouseNr, PlayerLastName = player.LastName, PlayerMailBox = player.MailBox, PlayerNr = player.PlayerNr,
                PlayerPhoneNr = player.PhoneNr, PlayerStreet = player.Street, PlayerYearOfJoin = player.YearOfJoin, PlayerZipcode = player.Zipcode,
                AllRoles = allRolesSelect, SelectedRoles = selectedRoles };
            return View(pvm);
        }

        // POST: /Player/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PlayerViewModel pvm)
        {
            if (ModelState.IsValid)
            {
                Player p = new Player
                {
                    BirthDay = pvm.PlayerBirthDay,
                    City = pvm.PlayerCity,
                    FederationNr = pvm.PlayerFederationNr,
                    FirstName = pvm.PlayerFirstName,
                    Gender = pvm.PlayerGender,
                    HouseNr = pvm.PlayerHouseNr,
                    Id = pvm.PlayerId,
                    LastName = pvm.PlayerLastName,
                    MailBox = pvm.PlayerMailBox,
                    PhoneNr = pvm.PlayerPhoneNr,
                    PlayerNr = pvm.PlayerNr,
                    Street = pvm.PlayerStreet,
                    YearOfJoin = pvm.PlayerYearOfJoin,
                    Zipcode = pvm.PlayerZipcode
                };
                p.Roles = new List<Role>();
                if (pvm.SelectedRoles != null && pvm.SelectedRoles.Count > 0)
                {
                    foreach (var r in pvm.SelectedRoles)
                    {
                        p.Roles.Add(roleRepo.getRoleById(r));
                    } 
                }
                repo.modifyPlayer(p);
                return RedirectToAction("Index");
            }
            var allRolesList = roleRepo.getRoles();
            var allRolesSelect = allRolesList.Select(o => new SelectListItem
            {
                Text = o.Name,
                Value = o.Id.ToString()
            });
            pvm.AllRoles = allRolesSelect;
            return View(pvm);
        }

        // GET: /Player/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Player player = repo.getPlayerById(id);
            if (player == null)
            {
                return HttpNotFound();
            }
            return View(player);
        }

        // POST: /Player/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            repo.deletePlayer(id);
            return RedirectToAction("Index");
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tennis.NET.Web/Controllers/TeamPlayerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tennis.NET.Models;
using Tennis.NET.DataModel;
using Tennis.NET.Repositories;

namespace Tennis.NET.Web.Controllers
{
    public class TeamPlayerController : Controller
    {
        private TeamPlayerRepository repo = new TeamPlayerRepository();
        private TeamRepository teamRepo = new TeamRepository();
        private PlayerRepository playerRepo = new PlayerRepository();
        private DivisionRepository divisionRepo = new DivisionRepository();

        // GET: /TeamPlayer/
        public ActionResult Index(int? divId, int? playerId, int? teamId)
        {
            List<TeamPlayer> teamPlayers = repo.getTeamPlayers();
            ViewBag.filter = false;
            if (divId != null)
            {
                ViewBag.filter = true;
                List<TeamPlayer> filteredList = new List<TeamPlayer>();
                foreach (TeamPlayer tp in teamPlayers)
                {
                    if (tp.DivisionId == divId)
                    {
                        filteredList.Add(tp);
                    }
                }
                teamPlayers = filteredList;
            }
            if (playerId != null)
            {
                ViewBag.filter = true;
                List<TeamPlayer> filteredList = new List<TeamPlayer>();
                foreach (TeamPlayer tp in teamPlayers)
                {
                    if (tp.PlayerId == playerId)
                    {
                        filteredList.Add(tp);
                    }
                }
                teamPlayers = filteredList;
            }
            if (teamId != null)
            {
                ViewBag.filter = true;
                List<TeamPlayer> filteredList = new List<TeamPlayer>();
                foreach (TeamPlayer tp in teamPlayers)
                {
                    if (tp.TeamId == teamId)
                    {
                        filteredList.Add(tp);
                    }
                }
                teamPlayers = filteredList;
            }
            return View(teamPlayers);
        }

        // GET: /TeamPlayer/Create
        public ActionResult Create()
        {
            ViewBag.DivId = new SelectList(divisionRepo.getDivisions(), "Id", "Name");
            ViewBag.PlId = new SelectList(playerRepo.getPlayers(), "Id", "FullName");
            ViewBag.TmId = new SelectList(teamRepo.getTeams(), "Id", "Name");
            return View();
        }

        // POST: /TeamPlayer/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="TeamId,PlayerId,DivisionId")] TeamPlayer teamplayer)
        {
            if (ModelState.IsValid)
            {
                repo.createTeamPlayer(teamplayer);
                return RedirectToAction("Index");
            }

            ViewBag.DivId = new SelectList(divisionRepo.getDivisions(), "Id", "Name", teamplayer.DivisionId);
            ViewBag.PlId = new SelectList(playerRepo.getPlayers(), "Id", "FullName", teamplayer.PlayerId);
            ViewBag.TmId = new SelectList(teamRepo.getTeams(), "Id", "Name", teamplayer.TeamId);
            return View(teamplayer);
        }

        // GET: /TeamPlayer/Delete/5
        public ActionResult Delete(int? playerId, int? divisionId, int? teamId)
        {
            if (playerId == null || divisionId == null || teamId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeamPlayer teamplayer = repo.getTeamPlayerById(playerId, divisionId, teamId);
            if (teamplayer == null)
            {
                return HttpNotFound();
            }
            return View(teamplayer);
        }

        // POST: /TeamPlayer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int playerId, int divisionId, int teamId)
        {
            repo.deleteTeamPlayer(playerId, divisionId, teamId);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                //db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tennis.NET.Web/Views/Player/Create.cshtml
@model Tennis.NET.Models.Player

@{
    ViewBag.Title = "Nieuwe speler aanmaken";
}

<h2>Nieuw</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Speler</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.PlayerNr, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PlayerNr)
                @Html.ValidationMessageFor(model => model.PlayerNr)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName)
                @Html.ValidationMessageFor(model => model.LastName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName)
                @Html.ValidationMessageFor(model => model.FirstName)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDay, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.BirthDay)
                @Html.ValidationMessageFor(model => model.BirthDay)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @foreach (var value in Enum.GetValues(typeof(Tennis.NET.Models.Gender)))
                {
                    @Html.RadioButtonFor(model => model.Gender, value.ToString())
                    @value.ToString()
                }
                @Html.ValidationMessageFor(model => model.Gender)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.YearOfJoin, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.YearOfJoin, Enumerable.Range(1950, DateTime.Today.Year - 1949).Select(i => new SelectListItem { Text = i.ToString(), Value = i.ToString() }), "Selecteer jaar", new { @class = "chosen-select" })
                @Html.ValidationMessageFor(model => model.YearOfJoin)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Street, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Street)
                @Html.ValidationMessageFor(model => model.Street)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HouseNr, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HouseNr)
                @Html.ValidationMessageFor(model => model.HouseNr)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MailBox, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MailBox)
                @Html.ValidationMessageFor(model => model.MailBox)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Zipcode, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Zipcode)
                @Html.ValidationMessageFor(model => model.Zipcode)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City)
                @Html.ValidationMessageFor(model => model.City)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNr, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNr)
                @Html.ValidationMessageFor(model => model.PhoneNr)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FederationNr, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FederationNr)
                @Html.ValidationMessageFor(model => model.FederationNr)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Opslaan" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Terug naar lijst", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval", "~/bundles/chosen")
    <script>
        $(".chosen-select").chosen({ width: "150px" })
        $("#BirthDay").datepicker({ maxDate: '-8Y', firstDay: 1, changeYear: true, changeMonth: true, yearRange: "-100:-8" });
    </script>
}

Tennis.NET.Web/Views/Player/Delete.cshtml
@model Tennis.NET.Models.Player

@{
    ViewBag.Title = "Speler verwijderen";
}

<h2>Verwijderen</h2>

<h3>Bent u zeker dat u deze speler wilt verwijderen?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlayerNr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlayerNr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FullName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FederationNr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FederationNr)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Verwijder" class="btn btn-default" /> |
            @Html.ActionLink("Terug naar lijst", "Index")
        </div>
    }
</div>

Tennis.NET.Web/Views/Player/Details.cshtml
@model Tennis.NET.Models.Player

@{
    ViewBag.Title = "Details speler";
}

<h2>Details</h2>

<div>
    <h4>Speler</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PlayerNr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PlayerNr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.YearOfJoin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.YearOfJoin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Street)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Street)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HouseNr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HouseNr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MailBox)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MailBox)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zipcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zipcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FederationNr)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FederationNr)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Roles)
        </dt>

        <dd>
            @foreach (var r in Model.Roles)
            {
                @r.Name
                <br/>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TeamPlayers)
        </dt>

        <dd>
            @foreach (var tp in Model.TeamPlayers)
            {
                @Html.Raw("Speelt voor \"")
                <b>@tp.Team.Name</b>
                @Html.Raw("\" in ")
                <b>@tp.Division.Name</b>
                <br/>
            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fines)
        </dt>

        <dd>
            @foreach (var f in Model.Fines)
            {
                @Html.Raw("Boete van € ")
                <b>@f.Amount</b>
                @Html.Raw(" op ")
                <b>@f.FineDate.ToShortDateString()</b>
                <br/>
            }
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Bewerken", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Terug naar lijst", "Index")
</p>

Tennis.NET.Web/Views/Player/Index.cshtml
@model IEnumerable<Tennis.NET.Models.Player>

@{
    ViewBag.Title = "Spelers";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Nieuwe speler aanmaken", "Create")
</p>
<table class="display" id="indexTbl">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.PlayerNr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FullName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BirthDay)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FederationNr)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PlayerNr)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FullName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BirthDay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PhoneNr)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FederationNr)
                </td>
                <td>
                    @Html.ActionLink("Bewerken", "Edit", new { id=item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                    @Html.ActionLink("Verwijderen", "Delete", new { id=item.Id }) |
                    @Html.ActionLink("Boetes", "Index", "Fine", new { playerId=item.Id}, null) |
                    @Html.ActionLink("Rollen", "Index", "Role", new { playerId=item.Id}, null) |
                    @Html.ActionLink("Activiteit", "Index", "TeamPlayer", new { playerId=item.Id}, null)
                </td>
            </tr>
        }
    </tbody>

</table>

@section Scripts {
    @Scripts.Render("~/bundles/datatables")
    <script>
        var table = $('#indexTbl').DataTable({ "language": { "url": "http://cdn.datatables.net/plug-ins/1.10.12/i18n/Dutch.json" } });
    </script>
}